### PR TITLE
tests:  add `nyc` coverage reports & utils tests

### PR DESCRIPTION
**Pull request by murrayee**
# What :computer: 
- Add tests coverage
- Add tests for util

# Why :hand:
- The more tests, the higher the quality
- Test reports help developers uncover missing tests

# Evidence :camera:
Include screenshots, screen recordings, or `console` output here demonstrating that your changes work as intended

# Notes :memo:
* Any notes/thoughts that the reviewers should know prior to reviewing the code?

### CODE REVIEW

**Comment by murrayee** [comment]
Hi.  This PR  already merged [zksync2-js/pull/39](https://github.com/zksync-sdk/zksync2-js/pull/39).

**Comment by murrayee** [comment]
> Hi. This PR already merged [zksync2-js/pull/39](https://github.com/zksync-sdk/zksync2-js/pull/39).

**Comment by danijelTxFusion** [comment]
I have already included all of the changes from that PR into main.

**Comment by murrayee** [comment]
> I have already included all of the changes from that PR into main. Also I have changed code coverage tool from `nyc` to `c8`.

Thanks team.

**Pull request closed without merging**
